// Generated by `swift run -c release CatPuzzleGenerator --ladder`.
// Do not edit by hand — regenerate instead (see Docs/LevelLadder.md).
//
// 3 cycles of 10 levels. Each cycle opens on an 8x8
// and climbs to a 10x10 at the next difficulty tier, then the next cycle
// starts over on a fresh 8x8.
public enum GeneratedLadderLevels {
    public static let fixtures: [LevelFixture] = [
        // #1 — cycle 1 slot 1, 8x8, blueprint easy, score 51, seed 20260932 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-01",
                size: 8,
                catCount: 8,
                maxMistakes: 3,
                regionIDs: [
                    [7, 7, 2, 1, 1, 1, 1, 0],
                    [7, 2, 2, 2, 2, 1, 1, 7],
                    [7, 2, 3, 3, 3, 3, 4, 7],
                    [7, 5, 3, 3, 4, 4, 4, 7],
                    [7, 5, 5, 5, 4, 7, 4, 7],
                    [7, 5, 5, 6, 6, 6, 7, 7],
                    [7, 7, 7, 7, 6, 6, 6, 7],
                    [7, 7, 7, 7, 7, 7, 7, 7],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 7),
                CellPosition(row: 1, column: 5),
                CellPosition(row: 2, column: 1),
                CellPosition(row: 3, column: 3),
                CellPosition(row: 4, column: 6),
                CellPosition(row: 5, column: 2),
                CellPosition(row: 6, column: 4),
                CellPosition(row: 7, column: 0),
            ]
        ),
        // #2 — cycle 1 slot 2, 9x9, blueprint medium, score 55, seed 20261175 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-02",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [8, 8, 8, 0, 0, 8, 8, 8, 8],
                    [8, 1, 1, 8, 8, 2, 8, 8, 8],
                    [8, 8, 3, 3, 3, 2, 8, 8, 8],
                    [8, 8, 3, 8, 8, 4, 4, 4, 8],
                    [5, 5, 5, 8, 8, 8, 4, 8, 8],
                    [5, 8, 8, 8, 8, 6, 6, 6, 8],
                    [8, 8, 8, 8, 7, 7, 7, 6, 8],
                    [8, 8, 8, 8, 7, 8, 8, 8, 8],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 3),
                CellPosition(row: 1, column: 1),
                CellPosition(row: 2, column: 5),
                CellPosition(row: 3, column: 2),
                CellPosition(row: 4, column: 6),
                CellPosition(row: 5, column: 0),
                CellPosition(row: 6, column: 7),
                CellPosition(row: 7, column: 4),
                CellPosition(row: 8, column: 8),
            ]
        ),
        // #3 — cycle 1 slot 3, 9x9, blueprint medium, score 56, seed 20261199 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-03",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [8, 8, 8, 8, 8, 0, 0, 8, 8],
                    [8, 1, 1, 8, 8, 8, 2, 8, 8],
                    [8, 3, 3, 3, 8, 8, 2, 8, 8],
                    [8, 3, 8, 8, 8, 4, 4, 4, 8],
                    [8, 5, 5, 5, 8, 8, 8, 4, 8],
                    [6, 6, 6, 5, 8, 8, 8, 8, 8],
                    [6, 8, 8, 8, 8, 8, 7, 7, 7],
                    [8, 8, 8, 8, 8, 8, 8, 8, 7],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 5),
                CellPosition(row: 1, column: 2),
                CellPosition(row: 2, column: 6),
                CellPosition(row: 3, column: 1),
                CellPosition(row: 4, column: 7),
                CellPosition(row: 5, column: 3),
                CellPosition(row: 6, column: 0),
                CellPosition(row: 7, column: 8),
                CellPosition(row: 8, column: 4),
            ]
        ),
        // #4 — cycle 1 slot 4, 9x9, blueprint easy, score 59, seed 20261242 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-04",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [2, 2, 0, 8, 1, 1, 1, 1, 1],
                    [8, 2, 2, 2, 8, 8, 8, 1, 8],
                    [8, 2, 8, 8, 3, 3, 3, 3, 8],
                    [8, 8, 4, 4, 4, 3, 5, 3, 8],
                    [8, 4, 4, 4, 5, 5, 5, 8, 8],
                    [7, 8, 8, 6, 6, 6, 5, 5, 8],
                    [7, 7, 7, 8, 6, 6, 8, 8, 8],
                    [7, 7, 8, 8, 8, 6, 8, 8, 8],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 2),
                CellPosition(row: 1, column: 7),
                CellPosition(row: 2, column: 1),
                CellPosition(row: 3, column: 5),
                CellPosition(row: 4, column: 3),
                CellPosition(row: 5, column: 6),
                CellPosition(row: 6, column: 4),
                CellPosition(row: 7, column: 0),
                CellPosition(row: 8, column: 8),
            ]
        ),
        // #5 — cycle 1 slot 5, 10x10, blueprint medium, score 62, seed 20261855 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-05",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 0, 0, 9, 9, 9, 9],
                    [9, 9, 9, 1, 1, 9, 2, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 2, 3, 3, 3],
                    [4, 4, 4, 9, 9, 9, 9, 9, 3, 9],
                    [9, 4, 9, 9, 5, 5, 5, 9, 9, 9],
                    [9, 9, 9, 9, 5, 9, 9, 6, 6, 6],
                    [7, 7, 7, 9, 9, 9, 9, 9, 9, 6],
                    [7, 9, 9, 9, 9, 9, 8, 8, 8, 9],
                    [9, 9, 9, 9, 9, 9, 9, 8, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 5),
                CellPosition(row: 1, column: 3),
                CellPosition(row: 2, column: 6),
                CellPosition(row: 3, column: 8),
                CellPosition(row: 4, column: 1),
                CellPosition(row: 5, column: 4),
                CellPosition(row: 6, column: 9),
                CellPosition(row: 7, column: 0),
                CellPosition(row: 8, column: 7),
                CellPosition(row: 9, column: 2),
            ]
        ),
        // #6 — cycle 1 slot 6, 10x10, blueprint medium, score 63, seed 20261815 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-06",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [0, 0, 9, 9, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 2, 9, 1, 1, 9, 9, 9],
                    [9, 9, 9, 2, 9, 3, 3, 3, 9, 9],
                    [9, 9, 4, 4, 4, 9, 9, 3, 9, 9],
                    [9, 9, 4, 9, 9, 9, 9, 5, 5, 5],
                    [9, 9, 9, 9, 9, 6, 6, 6, 9, 5],
                    [7, 7, 7, 9, 9, 9, 6, 9, 9, 9],
                    [9, 7, 9, 8, 8, 8, 9, 9, 9, 9],
                    [9, 9, 9, 9, 8, 9, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 0),
                CellPosition(row: 1, column: 5),
                CellPosition(row: 2, column: 3),
                CellPosition(row: 3, column: 7),
                CellPosition(row: 4, column: 2),
                CellPosition(row: 5, column: 9),
                CellPosition(row: 6, column: 6),
                CellPosition(row: 7, column: 1),
                CellPosition(row: 8, column: 4),
                CellPosition(row: 9, column: 8),
            ]
        ),
        // #7 — cycle 1 slot 7, 10x10, blueprint medium, score 63, seed 20261939 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-07",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 9, 9, 9, 0, 0, 9],
                    [1, 1, 9, 2, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 2, 9, 9, 9, 3, 3, 3],
                    [4, 4, 4, 9, 9, 9, 9, 9, 3, 9],
                    [4, 9, 5, 5, 5, 9, 9, 9, 9, 9],
                    [9, 6, 6, 6, 5, 9, 9, 9, 9, 9],
                    [9, 9, 6, 7, 7, 7, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 7, 9, 8, 8, 8],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 8],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 7),
                CellPosition(row: 1, column: 1),
                CellPosition(row: 2, column: 3),
                CellPosition(row: 3, column: 8),
                CellPosition(row: 4, column: 0),
                CellPosition(row: 5, column: 4),
                CellPosition(row: 6, column: 2),
                CellPosition(row: 7, column: 5),
                CellPosition(row: 8, column: 9),
                CellPosition(row: 9, column: 6),
            ]
        ),
        // #8 — cycle 1 slot 8, 10x10, blueprint easy, score 67, seed 20261886 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-08",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [1, 1, 1, 1, 1, 9, 2, 2, 9, 0],
                    [1, 9, 9, 9, 9, 2, 2, 2, 9, 9],
                    [3, 3, 3, 3, 3, 9, 2, 9, 9, 9],
                    [4, 4, 4, 9, 3, 5, 9, 9, 9, 9],
                    [4, 4, 9, 9, 5, 5, 5, 9, 9, 9],
                    [4, 9, 6, 6, 6, 5, 5, 9, 9, 9],
                    [9, 9, 9, 6, 6, 6, 7, 7, 7, 9],
                    [9, 9, 8, 8, 8, 8, 9, 7, 9, 9],
                    [9, 8, 8, 9, 9, 9, 9, 7, 7, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 9),
                CellPosition(row: 1, column: 0),
                CellPosition(row: 2, column: 6),
                CellPosition(row: 3, column: 4),
                CellPosition(row: 4, column: 1),
                CellPosition(row: 5, column: 5),
                CellPosition(row: 6, column: 3),
                CellPosition(row: 7, column: 7),
                CellPosition(row: 8, column: 2),
                CellPosition(row: 9, column: 8),
            ]
        ),
        // #9 — cycle 1 slot 9, 10x10, blueprint easy, score 69, seed 20261978 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-09",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [1, 1, 1, 1, 1, 2, 9, 9, 0, 9],
                    [1, 9, 2, 2, 2, 2, 9, 3, 9, 9],
                    [4, 9, 9, 2, 3, 3, 3, 3, 9, 9],
                    [4, 4, 4, 9, 9, 3, 9, 9, 5, 9],
                    [4, 4, 9, 9, 9, 9, 5, 5, 5, 9],
                    [9, 9, 6, 6, 6, 9, 9, 5, 5, 7],
                    [9, 9, 6, 9, 6, 6, 9, 7, 7, 7],
                    [9, 9, 9, 8, 8, 8, 9, 9, 9, 7],
                    [9, 9, 9, 8, 8, 8, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 8),
                CellPosition(row: 1, column: 0),
                CellPosition(row: 2, column: 3),
                CellPosition(row: 3, column: 5),
                CellPosition(row: 4, column: 1),
                CellPosition(row: 5, column: 7),
                CellPosition(row: 6, column: 2),
                CellPosition(row: 7, column: 9),
                CellPosition(row: 8, column: 4),
                CellPosition(row: 9, column: 6),
            ]
        ),
        // #10 — cycle 1 slot 10, 10x10, blueprint hard, score 82, seed 20262930 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-10",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 1, 0, 0, 0, 0, 0],
                    [9, 9, 9, 1, 1, 2, 2, 2, 2, 0],
                    [9, 9, 9, 9, 9, 2, 3, 3, 2, 4],
                    [9, 9, 9, 9, 9, 9, 3, 3, 3, 4],
                    [9, 5, 5, 5, 9, 9, 9, 4, 4, 4],
                    [9, 9, 5, 6, 6, 6, 9, 9, 9, 9],
                    [7, 7, 7, 9, 6, 9, 9, 9, 9, 9],
                    [7, 9, 9, 9, 9, 9, 9, 8, 8, 8],
                    [7, 9, 9, 9, 9, 9, 9, 9, 8, 8],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 6),
                CellPosition(row: 1, column: 3),
                CellPosition(row: 2, column: 5),
                CellPosition(row: 3, column: 7),
                CellPosition(row: 4, column: 9),
                CellPosition(row: 5, column: 2),
                CellPosition(row: 6, column: 4),
                CellPosition(row: 7, column: 0),
                CellPosition(row: 8, column: 8),
                CellPosition(row: 9, column: 1),
            ]
        ),
        // #11 — cycle 2 slot 1, 8x8, blueprint easy, score 51, seed 20260946 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-11",
                size: 8,
                catCount: 8,
                maxMistakes: 3,
                regionIDs: [
                    [2, 2, 7, 0, 1, 1, 1, 1],
                    [2, 2, 2, 7, 1, 7, 1, 7],
                    [2, 3, 3, 3, 7, 4, 7, 7],
                    [3, 3, 3, 4, 4, 4, 4, 7],
                    [5, 5, 5, 5, 4, 7, 7, 6],
                    [7, 5, 5, 7, 7, 6, 6, 6],
                    [7, 7, 7, 7, 6, 6, 7, 7],
                    [7, 7, 7, 7, 7, 7, 7, 7],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 3),
                CellPosition(row: 1, column: 6),
                CellPosition(row: 2, column: 0),
                CellPosition(row: 3, column: 2),
                CellPosition(row: 4, column: 4),
                CellPosition(row: 5, column: 1),
                CellPosition(row: 6, column: 5),
                CellPosition(row: 7, column: 7),
            ]
        ),
        // #12 — cycle 2 slot 2, 9x9, blueprint medium, score 55, seed 20261183 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-12",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [0, 0, 8, 8, 8, 8, 8, 8, 8],
                    [8, 8, 8, 8, 2, 8, 1, 1, 8],
                    [8, 8, 8, 8, 2, 8, 3, 3, 3],
                    [8, 8, 8, 8, 8, 4, 4, 4, 3],
                    [8, 8, 8, 8, 8, 4, 5, 5, 5],
                    [8, 6, 6, 6, 8, 8, 8, 5, 8],
                    [7, 7, 6, 8, 8, 8, 8, 8, 8],
                    [7, 8, 8, 8, 8, 8, 8, 8, 8],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 1),
                CellPosition(row: 1, column: 6),
                CellPosition(row: 2, column: 4),
                CellPosition(row: 3, column: 8),
                CellPosition(row: 4, column: 5),
                CellPosition(row: 5, column: 7),
                CellPosition(row: 6, column: 2),
                CellPosition(row: 7, column: 0),
                CellPosition(row: 8, column: 3),
            ]
        ),
        // #13 — cycle 2 slot 3, 9x9, blueprint medium, score 56, seed 20261207 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-13",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [8, 0, 0, 8, 8, 8, 8, 8, 8],
                    [8, 8, 8, 8, 8, 2, 8, 1, 1],
                    [8, 3, 3, 3, 8, 2, 8, 8, 8],
                    [8, 3, 8, 8, 8, 4, 4, 4, 8],
                    [5, 5, 5, 8, 8, 8, 4, 8, 8],
                    [5, 8, 6, 6, 6, 8, 8, 8, 8],
                    [8, 8, 8, 6, 8, 8, 7, 7, 7],
                    [8, 8, 8, 8, 8, 8, 8, 7, 8],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 2),
                CellPosition(row: 1, column: 8),
                CellPosition(row: 2, column: 5),
                CellPosition(row: 3, column: 1),
                CellPosition(row: 4, column: 6),
                CellPosition(row: 5, column: 0),
                CellPosition(row: 6, column: 3),
                CellPosition(row: 7, column: 7),
                CellPosition(row: 8, column: 4),
            ]
        ),
        // #14 — cycle 2 slot 4, 9x9, blueprint easy, score 60, seed 20261170 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-14",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [0, 8, 8, 8, 1, 1, 1, 1, 1],
                    [8, 2, 2, 2, 8, 3, 8, 8, 1],
                    [2, 2, 8, 8, 3, 3, 3, 3, 8],
                    [2, 8, 5, 8, 3, 4, 4, 4, 8],
                    [8, 5, 5, 5, 5, 4, 4, 4, 8],
                    [8, 8, 5, 6, 6, 6, 6, 6, 8],
                    [8, 8, 8, 8, 7, 7, 7, 6, 8],
                    [8, 8, 8, 8, 7, 7, 7, 8, 8],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 0),
                CellPosition(row: 1, column: 8),
                CellPosition(row: 2, column: 1),
                CellPosition(row: 3, column: 4),
                CellPosition(row: 4, column: 6),
                CellPosition(row: 5, column: 2),
                CellPosition(row: 6, column: 7),
                CellPosition(row: 7, column: 5),
                CellPosition(row: 8, column: 3),
            ]
        ),
        // #15 — cycle 2 slot 5, 10x10, blueprint medium, score 62, seed 20261863 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-15",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 9, 9, 9, 9, 0, 0],
                    [9, 9, 9, 2, 9, 1, 1, 9, 9, 9],
                    [9, 9, 9, 2, 3, 3, 3, 9, 9, 9],
                    [9, 9, 9, 9, 9, 3, 4, 4, 4, 9],
                    [5, 5, 5, 9, 9, 9, 9, 4, 9, 9],
                    [5, 9, 9, 6, 6, 6, 9, 9, 9, 9],
                    [9, 7, 7, 7, 6, 9, 9, 9, 9, 9],
                    [9, 7, 9, 9, 9, 9, 8, 8, 8, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 8, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 9),
                CellPosition(row: 1, column: 6),
                CellPosition(row: 2, column: 3),
                CellPosition(row: 3, column: 5),
                CellPosition(row: 4, column: 7),
                CellPosition(row: 5, column: 0),
                CellPosition(row: 6, column: 4),
                CellPosition(row: 7, column: 1),
                CellPosition(row: 8, column: 8),
                CellPosition(row: 9, column: 2),
            ]
        ),
        // #16 — cycle 2 slot 6, 10x10, blueprint medium, score 63, seed 20261823 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-16",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 9, 9, 9, 9, 0, 0],
                    [2, 9, 9, 1, 1, 9, 9, 9, 9, 9],
                    [2, 9, 9, 9, 9, 9, 9, 3, 3, 3],
                    [9, 9, 9, 9, 4, 4, 4, 9, 3, 9],
                    [5, 5, 5, 9, 9, 4, 9, 9, 9, 9],
                    [9, 5, 9, 9, 9, 9, 6, 6, 6, 9],
                    [9, 9, 9, 7, 7, 7, 6, 9, 9, 9],
                    [9, 8, 8, 8, 7, 9, 9, 9, 9, 9],
                    [9, 9, 8, 9, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 9),
                CellPosition(row: 1, column: 3),
                CellPosition(row: 2, column: 0),
                CellPosition(row: 3, column: 8),
                CellPosition(row: 4, column: 5),
                CellPosition(row: 5, column: 1),
                CellPosition(row: 6, column: 6),
                CellPosition(row: 7, column: 4),
                CellPosition(row: 8, column: 2),
                CellPosition(row: 9, column: 7),
            ]
        ),
        // #17 — cycle 2 slot 7, 10x10, blueprint medium, score 63, seed 20261943 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-17",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 9, 9, 9, 0, 0, 9],
                    [9, 9, 9, 9, 1, 1, 9, 9, 9, 2],
                    [3, 3, 3, 9, 9, 9, 9, 9, 9, 2],
                    [3, 9, 9, 4, 4, 4, 9, 9, 9, 9],
                    [9, 9, 9, 9, 4, 9, 9, 5, 5, 5],
                    [6, 6, 6, 9, 9, 9, 9, 9, 5, 9],
                    [9, 9, 6, 9, 9, 7, 7, 7, 9, 9],
                    [9, 9, 8, 8, 8, 9, 7, 9, 9, 9],
                    [9, 9, 9, 8, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 7),
                CellPosition(row: 1, column: 5),
                CellPosition(row: 2, column: 9),
                CellPosition(row: 3, column: 0),
                CellPosition(row: 4, column: 4),
                CellPosition(row: 5, column: 8),
                CellPosition(row: 6, column: 2),
                CellPosition(row: 7, column: 6),
                CellPosition(row: 8, column: 3),
                CellPosition(row: 9, column: 1),
            ]
        ),
        // #18 — cycle 2 slot 8, 10x10, blueprint easy, score 67, seed 20261898 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-18",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 1, 1, 1, 1, 1, 0, 2, 2, 9],
                    [9, 9, 1, 9, 9, 3, 2, 2, 2, 9],
                    [4, 9, 9, 9, 3, 3, 3, 2, 9, 9],
                    [4, 4, 4, 4, 9, 3, 3, 9, 9, 9],
                    [4, 5, 5, 5, 5, 9, 9, 6, 9, 6],
                    [9, 9, 5, 5, 9, 7, 9, 6, 6, 6],
                    [9, 9, 9, 7, 7, 7, 9, 9, 9, 6],
                    [8, 8, 8, 9, 7, 7, 9, 9, 9, 9],
                    [8, 8, 8, 9, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 6),
                CellPosition(row: 1, column: 2),
                CellPosition(row: 2, column: 7),
                CellPosition(row: 3, column: 5),
                CellPosition(row: 4, column: 0),
                CellPosition(row: 5, column: 3),
                CellPosition(row: 6, column: 9),
                CellPosition(row: 7, column: 4),
                CellPosition(row: 8, column: 1),
                CellPosition(row: 9, column: 8),
            ]
        ),
        // #19 — cycle 2 slot 9, 10x10, blueprint easy, score 70, seed 20261778 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-19",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [1, 1, 1, 0, 9, 9, 9, 9, 9, 9],
                    [1, 1, 1, 9, 9, 2, 2, 2, 2, 2],
                    [9, 9, 9, 9, 4, 9, 9, 2, 3, 3],
                    [9, 9, 4, 4, 4, 4, 3, 3, 3, 3],
                    [9, 6, 9, 9, 4, 5, 5, 5, 5, 5],
                    [9, 6, 6, 6, 9, 9, 9, 7, 5, 9],
                    [9, 8, 6, 6, 9, 9, 7, 7, 7, 9],
                    [8, 8, 8, 8, 9, 9, 7, 9, 9, 9],
                    [8, 9, 9, 9, 9, 9, 7, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 3),
                CellPosition(row: 1, column: 1),
                CellPosition(row: 2, column: 7),
                CellPosition(row: 3, column: 9),
                CellPosition(row: 4, column: 4),
                CellPosition(row: 5, column: 8),
                CellPosition(row: 6, column: 2),
                CellPosition(row: 7, column: 6),
                CellPosition(row: 8, column: 0),
                CellPosition(row: 9, column: 5),
            ]
        ),
        // #20 — cycle 2 slot 10, 10x10, blueprint hard, score 83, seed 20262872 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-20",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 1, 0, 0, 0, 0, 0],
                    [9, 9, 9, 1, 1, 2, 2, 2, 2, 0],
                    [9, 9, 9, 9, 9, 2, 3, 3, 2, 4],
                    [9, 9, 9, 9, 9, 9, 3, 3, 3, 4],
                    [5, 5, 5, 9, 9, 9, 9, 4, 4, 4],
                    [5, 9, 9, 9, 9, 9, 9, 6, 6, 6],
                    [7, 7, 7, 9, 9, 9, 9, 9, 6, 9],
                    [9, 9, 7, 8, 8, 8, 9, 9, 9, 9],
                    [9, 7, 7, 9, 8, 9, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 6),
                CellPosition(row: 1, column: 3),
                CellPosition(row: 2, column: 5),
                CellPosition(row: 3, column: 7),
                CellPosition(row: 4, column: 9),
                CellPosition(row: 5, column: 0),
                CellPosition(row: 6, column: 8),
                CellPosition(row: 7, column: 2),
                CellPosition(row: 8, column: 4),
                CellPosition(row: 9, column: 1),
            ]
        ),
        // #21 — cycle 3 slot 1, 8x8, blueprint easy, score 51, seed 20260952 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-21",
                size: 8,
                catCount: 8,
                maxMistakes: 3,
                regionIDs: [
                    [0, 2, 7, 1, 1, 1, 1, 1],
                    [2, 2, 2, 7, 1, 7, 3, 3],
                    [7, 7, 2, 2, 7, 3, 3, 3],
                    [7, 7, 7, 7, 4, 4, 4, 3],
                    [7, 5, 5, 5, 5, 4, 4, 4],
                    [7, 7, 7, 5, 6, 6, 6, 6],
                    [7, 7, 7, 5, 6, 7, 6, 7],
                    [7, 7, 7, 7, 7, 7, 7, 7],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 0),
                CellPosition(row: 1, column: 4),
                CellPosition(row: 2, column: 2),
                CellPosition(row: 3, column: 7),
                CellPosition(row: 4, column: 5),
                CellPosition(row: 5, column: 3),
                CellPosition(row: 6, column: 6),
                CellPosition(row: 7, column: 1),
            ]
        ),
        // #22 — cycle 3 slot 2, 9x9, blueprint medium, score 55, seed 20261187 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-22",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [8, 8, 8, 8, 8, 8, 8, 0, 0],
                    [1, 1, 2, 8, 8, 8, 8, 8, 8],
                    [8, 8, 2, 8, 3, 3, 3, 8, 8],
                    [8, 4, 4, 4, 8, 3, 8, 8, 8],
                    [8, 4, 8, 8, 8, 5, 5, 5, 8],
                    [8, 8, 8, 6, 6, 6, 5, 8, 8],
                    [8, 8, 8, 6, 8, 8, 7, 7, 7],
                    [8, 8, 8, 8, 8, 8, 8, 7, 8],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 8),
                CellPosition(row: 1, column: 0),
                CellPosition(row: 2, column: 2),
                CellPosition(row: 3, column: 5),
                CellPosition(row: 4, column: 1),
                CellPosition(row: 5, column: 6),
                CellPosition(row: 6, column: 3),
                CellPosition(row: 7, column: 7),
                CellPosition(row: 8, column: 4),
            ]
        ),
        // #23 — cycle 3 slot 3, 9x9, blueprint medium, score 56, seed 20261223 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-23",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [0, 0, 8, 8, 8, 8, 8, 8, 8],
                    [8, 8, 8, 8, 8, 8, 1, 1, 2],
                    [8, 8, 8, 8, 3, 3, 3, 8, 2],
                    [4, 4, 4, 8, 8, 3, 8, 8, 8],
                    [4, 8, 8, 5, 5, 5, 8, 8, 8],
                    [8, 6, 6, 6, 5, 8, 8, 8, 8],
                    [8, 8, 6, 8, 8, 8, 7, 7, 7],
                    [8, 8, 8, 8, 8, 8, 8, 7, 8],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 1),
                CellPosition(row: 1, column: 6),
                CellPosition(row: 2, column: 8),
                CellPosition(row: 3, column: 5),
                CellPosition(row: 4, column: 0),
                CellPosition(row: 5, column: 4),
                CellPosition(row: 6, column: 2),
                CellPosition(row: 7, column: 7),
                CellPosition(row: 8, column: 3),
            ]
        ),
        // #24 — cycle 3 slot 4, 9x9, blueprint easy, score 61, seed 20261138 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-24",
                size: 9,
                catCount: 9,
                maxMistakes: 3,
                regionIDs: [
                    [2, 8, 8, 1, 1, 1, 1, 8, 0],
                    [2, 2, 2, 8, 1, 1, 8, 3, 3],
                    [2, 2, 8, 4, 8, 8, 3, 3, 3],
                    [8, 8, 4, 4, 4, 4, 5, 3, 8],
                    [8, 6, 8, 8, 4, 5, 5, 5, 8],
                    [6, 6, 6, 6, 8, 8, 5, 5, 8],
                    [7, 7, 6, 8, 8, 8, 8, 8, 8],
                    [7, 7, 7, 7, 8, 8, 8, 8, 8],
                    [8, 8, 8, 8, 8, 8, 8, 8, 8],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 8),
                CellPosition(row: 1, column: 5),
                CellPosition(row: 2, column: 1),
                CellPosition(row: 3, column: 7),
                CellPosition(row: 4, column: 4),
                CellPosition(row: 5, column: 6),
                CellPosition(row: 6, column: 2),
                CellPosition(row: 7, column: 0),
                CellPosition(row: 8, column: 3),
            ]
        ),
        // #25 — cycle 3 slot 5, 10x10, blueprint medium, score 62, seed 20261871 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-25",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 9, 0, 0, 9, 9, 9],
                    [9, 1, 1, 9, 9, 9, 9, 9, 2, 9],
                    [9, 9, 9, 9, 3, 3, 3, 9, 2, 9],
                    [9, 4, 4, 4, 9, 3, 9, 9, 9, 9],
                    [9, 9, 4, 9, 9, 9, 9, 5, 5, 5],
                    [9, 6, 6, 6, 9, 9, 9, 9, 9, 5],
                    [7, 7, 7, 6, 9, 9, 9, 9, 9, 9],
                    [7, 9, 9, 9, 9, 9, 9, 8, 8, 8],
                    [9, 9, 9, 9, 9, 9, 9, 8, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 6),
                CellPosition(row: 1, column: 1),
                CellPosition(row: 2, column: 8),
                CellPosition(row: 3, column: 5),
                CellPosition(row: 4, column: 2),
                CellPosition(row: 5, column: 9),
                CellPosition(row: 6, column: 3),
                CellPosition(row: 7, column: 0),
                CellPosition(row: 8, column: 7),
                CellPosition(row: 9, column: 4),
            ]
        ),
        // #26 — cycle 3 slot 6, 10x10, blueprint medium, score 63, seed 20261827 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-26",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [0, 0, 9, 9, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 2, 9, 9, 9, 9, 1, 1],
                    [9, 9, 9, 2, 3, 3, 3, 9, 9, 9],
                    [9, 9, 4, 4, 4, 9, 3, 9, 9, 9],
                    [9, 9, 4, 9, 9, 5, 5, 5, 9, 9],
                    [6, 6, 6, 9, 9, 9, 9, 5, 9, 9],
                    [6, 9, 9, 7, 7, 7, 9, 9, 9, 9],
                    [9, 9, 9, 9, 7, 9, 9, 8, 8, 8],
                    [9, 9, 9, 9, 9, 9, 9, 9, 8, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 1),
                CellPosition(row: 1, column: 9),
                CellPosition(row: 2, column: 3),
                CellPosition(row: 3, column: 6),
                CellPosition(row: 4, column: 2),
                CellPosition(row: 5, column: 7),
                CellPosition(row: 6, column: 0),
                CellPosition(row: 7, column: 4),
                CellPosition(row: 8, column: 8),
                CellPosition(row: 9, column: 5),
            ]
        ),
        // #27 — cycle 3 slot 7, 10x10, blueprint medium, score 63, seed 20261947 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-27",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 9, 9, 9, 9, 0, 0],
                    [1, 1, 9, 9, 9, 9, 9, 2, 9, 9],
                    [9, 9, 9, 3, 3, 3, 9, 2, 9, 9],
                    [9, 9, 9, 9, 3, 9, 4, 4, 4, 9],
                    [9, 5, 5, 5, 9, 9, 4, 9, 9, 9],
                    [9, 5, 9, 9, 9, 9, 9, 6, 6, 6],
                    [9, 7, 7, 7, 9, 9, 9, 9, 9, 6],
                    [9, 9, 7, 9, 9, 8, 8, 8, 9, 9],
                    [9, 9, 9, 9, 9, 8, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 8),
                CellPosition(row: 1, column: 0),
                CellPosition(row: 2, column: 7),
                CellPosition(row: 3, column: 4),
                CellPosition(row: 4, column: 6),
                CellPosition(row: 5, column: 1),
                CellPosition(row: 6, column: 9),
                CellPosition(row: 7, column: 2),
                CellPosition(row: 8, column: 5),
                CellPosition(row: 9, column: 3),
            ]
        ),
        // #28 — cycle 3 slot 8, 10x10, blueprint easy, score 67, seed 20261910 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-28",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 9, 9, 0, 1, 1, 1, 1, 1],
                    [9, 2, 2, 2, 2, 9, 1, 9, 3, 3],
                    [9, 2, 4, 9, 2, 9, 9, 3, 3, 3],
                    [9, 4, 4, 4, 9, 9, 9, 9, 5, 3],
                    [9, 4, 4, 6, 9, 9, 5, 5, 5, 5],
                    [9, 6, 6, 6, 9, 9, 9, 7, 5, 9],
                    [9, 9, 9, 6, 6, 9, 7, 7, 7, 9],
                    [8, 8, 8, 9, 9, 9, 9, 7, 7, 9],
                    [8, 8, 8, 9, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 4),
                CellPosition(row: 1, column: 6),
                CellPosition(row: 2, column: 1),
                CellPosition(row: 3, column: 9),
                CellPosition(row: 4, column: 2),
                CellPosition(row: 5, column: 8),
                CellPosition(row: 6, column: 3),
                CellPosition(row: 7, column: 7),
                CellPosition(row: 8, column: 0),
                CellPosition(row: 9, column: 5),
            ]
        ),
        // #29 — cycle 3 slot 9, 10x10, blueprint easy, score 70, seed 20261834 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-29",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [2, 9, 9, 1, 1, 1, 1, 0, 9, 9],
                    [2, 2, 2, 9, 9, 1, 1, 9, 3, 9],
                    [9, 2, 9, 4, 9, 3, 3, 3, 3, 9],
                    [9, 2, 9, 4, 4, 4, 3, 5, 9, 9],
                    [9, 9, 9, 4, 4, 5, 5, 5, 5, 9],
                    [6, 6, 6, 9, 9, 9, 9, 9, 5, 9],
                    [6, 6, 7, 7, 7, 7, 7, 9, 9, 9],
                    [9, 6, 9, 7, 9, 9, 9, 8, 8, 8],
                    [9, 9, 9, 9, 9, 9, 9, 8, 8, 8],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 7),
                CellPosition(row: 1, column: 5),
                CellPosition(row: 2, column: 1),
                CellPosition(row: 3, column: 6),
                CellPosition(row: 4, column: 4),
                CellPosition(row: 5, column: 8),
                CellPosition(row: 6, column: 0),
                CellPosition(row: 7, column: 3),
                CellPosition(row: 8, column: 9),
                CellPosition(row: 9, column: 2),
            ]
        ),
        // #30 — cycle 3 slot 10, 10x10, blueprint hard, score 84, seed 20262858 dominantBackground
        LevelFixture(
            level: LevelDefinition(
                id: "ladder-30",
                size: 10,
                catCount: 10,
                maxMistakes: 3,
                regionIDs: [
                    [9, 9, 1, 0, 0, 9, 9, 9, 9, 9],
                    [9, 1, 1, 2, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 2, 9, 9, 9, 9, 9, 9],
                    [9, 9, 9, 9, 3, 3, 3, 9, 9, 9],
                    [5, 5, 5, 9, 9, 4, 4, 4, 9, 9],
                    [5, 6, 6, 6, 9, 9, 9, 9, 9, 9],
                    [9, 9, 6, 9, 9, 9, 9, 7, 7, 7],
                    [9, 9, 9, 9, 9, 9, 8, 8, 8, 7],
                    [9, 9, 9, 9, 9, 9, 8, 9, 9, 7],
                    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
                ]
            ),
            solution: [
                CellPosition(row: 0, column: 4),
                CellPosition(row: 1, column: 1),
                CellPosition(row: 2, column: 3),
                CellPosition(row: 3, column: 5),
                CellPosition(row: 4, column: 7),
                CellPosition(row: 5, column: 0),
                CellPosition(row: 6, column: 2),
                CellPosition(row: 7, column: 9),
                CellPosition(row: 8, column: 6),
                CellPosition(row: 9, column: 8),
            ]
        ),
    ]

    public static let all = fixtures.map(\.level)

    /// Levels per difficulty cycle. Progress wraps back to the first level
    /// once every shipped level is complete.
    public static let levelsPerCycle = 10
}
